version: "3"

services:
  summerjob-web:
    container_name: summerjob-web
    hostname: summerjob-web
    image: "ghcr.io/ladal1/summerjob-web:latest"
    restart: unless-stopped
    networks:
      - summerjob-network
      # - additional networks for reverse proxy or specify open ports below
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@summerjob-db:5432/${POSTGRES_DB}?schema=public
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_FROM=${EMAIL_FROM}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - NEXTAUTH_URL=https://planner.summerjob.eu # Domain of the deployed web app, or http://localhost:3000 if running locally
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET} # Generate a random string with `openssl rand -base64 32`
      - AMQP_URL=${AMQP_URL}
      - QUEUE_NAME=${QUEUE_NAME}
      - UPLOAD_DIR=../web-storage
    ports:
      - 3000:3000
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web-storage:/web-storage
    depends_on:
      - summerjob-db
      - summerjob-amqp

  summerjob-db:
    container_name: summerjob-db
    hostname: summerjob-db
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - summerjob-network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped

  summerjob-planner:
    container_name: summerjob-planner
    hostname: summerjob-planner
    image: "ghcr.io/ladal1/summerjob-planner:latest"
    restart: on-failure:5
    environment:
      - AMQP_URL=${AMQP_URL}
      - QUEUE_NAME=${QUEUE_NAME}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@summerjob-db:5432/${POSTGRES_DB}?schema=public
    networks:
      - summerjob-network
    build:
      context: planner
      dockerfile: Dockerfile
    depends_on:
      summerjob-db:
        condition: service_started
      summerjob-amqp:
        condition: service_healthy

  summerjob-amqp:
    container_name: summerjob-amqp
    hostname: summerjob-amqp
    image: rabbitmq:3.11
    restart: unless-stopped
    networks:
      - summerjob-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 15s
      timeout: 10s
      retries: 10

networks:
  summerjob-network:

volumes:
  postgres:
