version: "3"

services:
  summerjob-scripts:
    container_name: summerjob-scripts
    hostname: summerjob-scripts
    image: summerjob/scripts
    networks:
      - summerjob_summerjob-network
    ports:
      - 5555:5555
    environment:
      - DATABASE_URL=postgresql://username:password@summerjob-db:5432/summerjob?schema=public
    stdin_open: true
    tty: true
    build:
      context: ../web
      dockerfile: ./Dockerfile.scripts

networks:
  summerjob_summerjob-network:
    external: true
